<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>common</artifactId>
        <groupId>com.lanf</groupId>
        <version>1.0.0</version>
    </parent>

    <artifactId>common-cache</artifactId>
    <version>${common-redos.version}</version>
    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-util</artifactId>
            <version>${common-util.version}</version>
        </dependency>

        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-constant</artifactId>
            <version>${common-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-lock</artifactId>
            <version>${common-lock.version}</version>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.39.0</version> <!-- 建议使用最新稳定版 -->
        </dependency>

    </dependencies>

</project>