package com.lanf.storage.mq.constant;

public class StorageMqGroupName {
    /**
     * 回收预售库存
     */
    public static final String RECYCLE_STOCK_GROUP = "RECYCLE_STOCK_GROUP";

    /**
     * 添加销售出库单
     */
    public static final String ADD_SALES_OUT_STOCK_ORDER_GROUP = "ADD_SALES_OUT_STOCK_ORDER_GROUP";

    public static final String ORDER_CREATE_SUCCESS_EVENT_ADD_RECONCILIATION_ORDER_GROUP = "ORDER_CREATE_SUCCESS_EVENT_ADD_RECONCILIATION_ORDER_GROUP";

    public static final String ADD_RECONCILIATION_ORDER_GROUP = "ADD_RECONCILIATION_ORDER_GROUP";

    public static final String ORDER_OUT_BOUNDED_EVENT_ADD_RECONCILIATION_ORDER_GROUP = "ORDER_OUT_BOUNDED_EVENT_ADD_RECONCILIATION_ORDER_GROUP";
    public static final String ORDER_CANCEL_EVENT_ADD_RECONCILIATION_ORDER_GROUP = "ORDER_CANCEL_EVENT_ADD_RECONCILIATION_ORDER_GROUP";

    public static final String SHORT_STOCK_RECONCILIATION_GROUP = "SHORT_STOCK_RECONCILIATION_GROUP";

    /**
     * 长库存对账
     */
    public static final String LONG_STOCK_RECONCILIATION_GROUP = "LONG_STOCK_RECONCILIATION_GROUP";


}
