<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lanf</groupId>
        <artifactId>service</artifactId>
        <version>${service-pom.version}</version>
    </parent>

    <artifactId>service-search</artifactId>
    <version>${service-search.version}</version>
    <dependencies>
        <!-- Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <!-- Nacos Discovery -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-elasticsearch</artifactId>
            <version>${common-elasticsearch.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <version>${spring-web.version}</version>
            <artifactId>spring-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-util</artifactId>
            <version>${common-util.version}</version>
        </dependency>

        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-rocketmq</artifactId>
            <version>${common-rocketmq.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>service-api-search</artifactId>
            <version>${service-search.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-mybatis</artifactId>
            <version>${common-mybatis.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>


</project>