<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lanf</groupId>
        <artifactId>base-mf</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <packaging>pom</packaging>
    <artifactId>service</artifactId>
    <version>${service.version}</version>
    <properties>
        <service.version>1.0.0-SNAPSHOT</service.version>
    </properties>
    <modules>
        <module>service-system</module>
        <module>service-log</module>
        <module>service-logistics</module>
        <module>service-file</module>
        <module>service-storage</module>
        <module>service-goods</module>
        <module>service-user</module>
        <module>service-order</module>
        <module>service-pay</module>
        <module>service-sms</module>
        <module>service-welfare</module>
        <module>service-aftersales</module>
        <module>service-finance</module>
        <module>service-search</module>
        <module>service-seckill</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-system</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-log</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-logistics</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-file</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-storage</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-goods</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-user</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-order</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-pay</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-sms</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-welfare</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-aftersales</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-finance</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-search</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lanf</groupId>
                <artifactId>service-seckill</artifactId>
                <version>${service.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-start</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.6.2</version>
        </dependency>
    </dependencies>
</project>