<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lanf</groupId>
        <artifactId>service-api</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>service-api-storage</artifactId>
    <version>${service-storage.version}</version>
    <dependencies>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.6.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-mybatis</artifactId>
            <version>${common-mybatis.version}</version>
        </dependency>
    </dependencies>

</project>