<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.lanf</groupId>
        <artifactId>service</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>service-system</artifactId>
    <version>${service-system.version}</version>


    <dependencies>

        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>spring-security</artifactId>
            <version>${ispring-serurity.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>


        <!-- Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <!-- Nacos Discovery -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-util</artifactId>
            <version>${common-util.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-constant</artifactId>
            <version>${common-core.version}</version>

        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.lanf</groupId>-->
<!--            <artifactId>common-log</artifactId>-->
<!--            <version>${common-log.version}</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-mybatis</artifactId>
            <version>${common-mybatis.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-biz-cache</artifactId>
            <version>${common-biz-cache.version}</version>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.6.2</version>
        </dependency>
        <!--打印skywalking的TraceId到日志-->
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>7.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
            <version>7.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.lanf</groupId>
            <artifactId>common-lock</artifactId>
            <version>${common-lock.version}</version>
        </dependency>

    </dependencies>




</project>